steps:
  # Sprint 3 Phase 3: Verify metrics configuration before deployment
  # Following Andrew Ng's "Test everything" principle
  - name: 'python:3.11-slim'
    id: 'verify-metrics-config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "========================================"
        echo "METRICS CONFIGURATION VERIFICATION"
        echo "Sprint 3 Phase 3: Pre-deployment check"
        echo "========================================"

        # Install dependencies
        pip install --quiet google-cloud-monitoring==2.15.1 pydantic-settings fastapi

        # Run metrics verification script
        python3 scripts/verify_metrics_config.py

        # Exit code 0 = pass, 1 = fail (blocks deployment)
    dir: 'backend'
    waitFor: ['-']  # Run first, before any other step

  # Run metrics tests (Sprint 3 Phase 2 test suite)
  - name: 'python:3.11-slim'
    id: 'test-metrics'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "========================================"
        echo "METRICS TEST SUITE (40 tests)"
        echo "Sprint 3 Phase 2: Comprehensive coverage"
        echo "========================================"

        # Install dependencies
        pip install --quiet -r requirements.txt
        pip install --quiet pytest pytest-cov

        # Run metrics tests
        pytest tests/test_metrics.py -v --tb=short

        echo ""
        echo "✓ All 40 metrics tests passed"
    dir: 'backend'
    waitFor: ['verify-metrics-config']  # Run after verification

  # Build the push worker container image (only runs after verification passes)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/vividly/push-worker:${BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/vividly/push-worker:latest'
      - '-f'
      - 'Dockerfile.push-worker'
      - '.'
    waitFor: ['test-metrics']  # Wait for tests

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-build-id'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/vividly/push-worker:${BUILD_ID}'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-latest'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/vividly/push-worker:latest'
    waitFor: ['build-image']


options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/vividly/push-worker:${BUILD_ID}'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/vividly/push-worker:latest'
