# Cloud Build configuration for Backend API
# Builds Docker image and deploys to Cloud Run

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: ${_ENVIRONMENT}-vividly-api
  _REPOSITORY: ${_ENVIRONMENT}-vividly-images
  _IMAGE_NAME: backend-api

steps:
  # Sprint 3 Phase 3: Verify metrics configuration before deployment
  # Following Andrew Ng's "Test everything" principle
  - name: 'python:3.11-slim'
    id: 'verify-metrics-config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "========================================"
        echo "METRICS CONFIGURATION VERIFICATION"
        echo "Sprint 3 Phase 3: Pre-deployment check"
        echo "========================================"

        # Install dependencies
        pip install --quiet google-cloud-monitoring==2.15.1 pydantic-settings fastapi

        # Run metrics verification script
        python3 scripts/verify_metrics_config.py

        # Exit code 0 = pass, 1 = fail (blocks deployment)
    dir: 'backend'
    waitFor: ['-']  # Run first, before any other step

  # Run metrics tests (Sprint 3 Phase 2 test suite)
  - name: 'python:3.11-slim'
    id: 'test-metrics'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "========================================"
        echo "METRICS TEST SUITE (40 tests)"
        echo "Sprint 3 Phase 2: Comprehensive coverage"
        echo "========================================"

        # Install dependencies
        pip install --quiet -r requirements.txt
        pip install --quiet pytest pytest-cov

        # Run metrics tests
        pytest tests/test_metrics.py -v --tb=short

        echo ""
        echo "✓ All 40 metrics tests passed"
    dir: 'backend'
    waitFor: ['verify-metrics-config']  # Run after verification

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-sha'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-latest'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    waitFor: ['push-image-sha', 'push-image-latest', 'test-metrics']
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'

  # Run database migrations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - '${_SERVICE_NAME}-migrate-${BUILD_ID}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--command=alembic'
      - '--args=upgrade,head'
      - '--set-env-vars=ENVIRONMENT=${_ENVIRONMENT}'
      - '--set-secrets=DATABASE_URL=database-url-${_ENVIRONMENT}:latest'
      - '--vpc-connector=projects/${PROJECT_ID}/locations/${_REGION}/connectors/${_ENVIRONMENT}-cloud-run-connector'
      - '--service-account=${_ENVIRONMENT}-cloud-run-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--execute-now'
      - '--wait'
    dir: 'backend'

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
