#!/usr/bin/env python3
"""
Create Demo Super Admin User via SQL

Generates SQL statements with properly hashed passwords to create a demo super admin account.

USAGE:
    # Generate SQL and save to file
    cd /Users/richedwards/AI-Dev-Projects/Vividly/backend
    source venv/bin/activate
    python3 ../scripts/create_demo_superadmin_via_sql.py > /tmp/create_user.sql

    # Execute the SQL using psql (RECOMMENDED METHOD)
    export PGPASSWORD="VividlyTest2025Simple"
    /opt/homebrew/opt/postgresql@15/bin/psql \
        -h "34.56.211.136" \
        -U "vividly" \
        -d "vividly" \
        -f /tmp/create_user.sql

For detailed database access instructions, see:
    /Users/richedwards/AI-Dev-Projects/Vividly/docs/database_access.md
"""
import sys
import os
from pathlib import Path

# Add backend to path
backend_path = Path(__file__).parent.parent / "backend"
sys.path.insert(0, str(backend_path))

from app.core.security import get_password_hash
import uuid

# Generate user data
user_id = str(uuid.uuid4())
email = "admin@vividly.demo"
password = "VividlyAdmin2024!"
hashed_password = get_password_hash(password)
first_name = "Super"
last_name = "Admin"

# IMPORTANT: Use correct enum values and column names
# See database schema: password_hash (not hashed_password), status (not is_active)
# UserRole enum: STUDENT, TEACHER, ADMIN, SUPER_ADMIN
# UserStatus enum: ACTIVE, SUSPENDED, PENDING, ARCHIVED
role = "SUPER_ADMIN"  # Must match enum exactly
status = "ACTIVE"     # Must match enum exactly

# Print SQL commands
print("-- SQL commands to create demo super admin user")
print("-- Generated by: scripts/create_demo_superadmin_via_sql.py")
print()
print("-- First, check if user exists and delete if necessary")
print(f"DELETE FROM users WHERE email = '{email}';")
print()
print("-- Insert new super admin user")
print(f"""INSERT INTO users (
    user_id,
    email,
    password_hash,
    first_name,
    last_name,
    role,
    status,
    created_at,
    updated_at
) VALUES (
    '{user_id}',
    '{email}',
    '{hashed_password}',
    '{first_name}',
    '{last_name}',
    '{role}',
    '{status}',
    NOW(),
    NOW()
);""")
print()
print("-- Verify user was created")
print(f"SELECT user_id, email, role, status FROM users WHERE email = '{email}';")
print()
print("=" * 60)
print("DEMO SUPER ADMIN CREDENTIALS")
print("=" * 60)
print(f"Email:    {email}")
print(f"Password: {password}")
print(f"Role:     {role}")
print(f"Status:   {status}")
print(f"User ID:  {user_id}")
print("=" * 60)
print()
print("To execute this SQL:")
print("  export PGPASSWORD='VividlyTest2025Simple'")
print("  /opt/homebrew/opt/postgresql@15/bin/psql \\")
print("    -h '34.56.211.136' \\")
print("    -U 'vividly' \\")
print("    -d 'vividly' \\")
print("    -f /tmp/create_user.sql")
