name: Integration Tests

on:
  # Run after deployments
  workflow_run:
    workflows: ["Deploy Backend to Dev", "Deploy Frontend to Dev"]
    types:
      - completed

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    # Only run if the workflow that triggered this was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: read
      id-token: write

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Get Frontend URL
        id: frontend-url
        run: |
          FRONTEND_URL=$(gcloud run services describe ${{ env.ENVIRONMENT }}-vividly-frontend \
            --region=us-central1 \
            --project=vividly-${{ env.ENVIRONMENT }}-rich \
            --format="value(status.url)")
          echo "url=$FRONTEND_URL" >> $GITHUB_OUTPUT
          echo "Frontend URL: $FRONTEND_URL"

      - name: Get Backend URL
        id: backend-url
        run: |
          BACKEND_URL=$(gcloud run services describe ${{ env.ENVIRONMENT }}-vividly-api \
            --region=us-central1 \
            --project=vividly-${{ env.ENVIRONMENT }}-rich \
            --format="value(status.url)")
          echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT
          echo "Backend URL: $BACKEND_URL"

      - name: Run Integration Tests
        env:
          FRONTEND_URL: ${{ steps.frontend-url.outputs.url }}
          BACKEND_URL: ${{ steps.backend-url.outputs.url }}
          TEST_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        run: |
          chmod +x scripts/verify-deployment.sh
          ./scripts/verify-deployment.sh \
            --frontend-url "$FRONTEND_URL" \
            --backend-url "$BACKEND_URL" \
            --environment "$ENVIRONMENT" \
            --test-email "$TEST_EMAIL" \
            --test-password "$TEST_PASSWORD"

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Integration Tests Failed - ${process.env.ENVIRONMENT}`,
              body: `Integration tests failed for ${process.env.ENVIRONMENT} environment.\n\nWorkflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              labels: ['bug', 'integration-test-failure', process.env.ENVIRONMENT]
            })
